### ISSUE TITLE
Implement One Page scroll on Desktop

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#10]
**What:** Implement One Page scroll on Desktop

![image](https://user-images.githubusercontent.com/849872/63067437-9560bd00-bed4-11e9-85bb-1ed480d2ba0d.png)

**How:**

- Research a library that implements this behavior
- Use that library to implement one-page scroll
- This should only work on Desktop

**Comment by duranmla** [comment]
This doesn't seems to add value any more.
