### ISSUE TITLE
Integrate Header

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#12]
**What:** Integrate Header

We will be integrating the header component https://github.com/debtcollective/header, but we will template it so it looks like designs. Functionality wise it will stay the same.

**How:**

- Integrate Header component
- The session should work correctly with Discourse

**Comment by duranmla** [comment]
We are going to update the expectations of this integrations and instead we are going to use the header that we created for academics letter at https://github.com/debtcollective/academics-letter/tree/master/src/components/Header
