### ISSUE TITLE
Page should render correctly on Mobile devices

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#15]
Let's use BrowserStack for this

**Comment by duranmla** [comment]
As _"mobile devices"_ is a too broad spectrum, I come to check our metrics to see what are our priorities _(AKA the browsers and devices mostly people use to visit our app)_

- [Browsers mostly used within the last month](https://user-images.githubusercontent.com/1425162/72219556-9cedc600-3547-11ea-945c-a5859eb40e46.png) Chrome and Safari are the most used
- [Devices mostly used within the last month (desktop, mobile, tablet)](https://user-images.githubusercontent.com/1425162/72219564-b7c03a80-3547-11ea-9483-94728ea897f3.png) Almost 50:50 for desktop and mobile
- [Device model most used](https://user-images.githubusercontent.com/1425162/72219583-ed652380-3547-11ea-842b-e7b3d3277c62.png) iPhone is by far the most used device

With that in mind I am going to check on browser stack latest version of Chrome, Safari in desktop and mobile iPhone to make sure we have the site render properly. Then, I will take a random Android device with latest OS to se the state of the page there.

**Comment by duranmla** [comment]
The first iteration over the current implementation has the following results.
- [ ] [Data dues form layout looks miss aligned / broken](https://user-images.githubusercontent.com/1425162/72272145-72c00500-3628-11ea-954d-3914e7866928.png)
- [ ] [Actions list looks not uniform](https://user-images.githubusercontent.com/1425162/72272166-76ec2280-3628-11ea-8f7b-f5466193970b.png)
- [ ] [Header profile is too tight](https://user-images.githubusercontent.com/1425162/72272169-79e71300-3628-11ea-9e69-f141d3a9dab8.png)
- [ ] [Share component overlap footer](https://user-images.githubusercontent.com/1425162/72272200-8bc8b600-3628-11ea-9979-0d2e9e9e4ccb.png)
- [ ] [Share component overlap "news" notification](https://user-images.githubusercontent.com/1425162/72272405-d9452300-3628-11ea-908e-125ddc718ec1.png)

**Comment by duranmla** [comment]
Priorities has changes and I am going to be working on the Discourse customisation. In that sense, this one remains pending.

**Comment by duranmla** [comment]
I have also added a card on asana to make easier for product to prioritise this activity.
