### ISSUE TITLE
Landing page Join Campaign sections show the actual number of people that have joined to the campaign

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#19]

**Comment by duranmla** [comment]
I think this is a mistake this issue hasn't been addressed yet. @orlando

**Comment by orlando** [comment]
@duranmla looks like is a commit from the old history? Not sure. Let’s reopen it

**Comment by duranmla** [comment]
After the above PR gets merged what w need to do is to consume it in order to have the numbers as expected by this ticket
