### ISSUE TITLE
Research CMS Implementation

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#2]
**What:** Research CMS Implementation

**Why:** We need a CMS for the campaign page, this to allow admins to change the text without needing a developer. 

**How:** Research the different options and evaluate them. Write a small spec about this and let's discuss it with the rest of the team to settle on a solution.

## Notes
After we decide what CMS we will use, we will create more tickets to cover implementation

**Comment by duranmla** [comment]
I made a research which I [summarised here](https://www.notion.so/duranmla/2-Research-CMS-Implementation-f94e2bc969dd4888baf01d5b9d140310) I also made some small prototypes configuring a dummy site for testing and the bottom line is:

> For me Netlify is the winner, we have a lot in the Netlify project dashboard, I like to have the admin within the same page, we support roles, we have analytics and lambda functions.
>
> Yes, many of those features are from Netlify panel and no the CMS itself but I don't see too much of the difference more than just aesthetics from using Prismic and NetlifyCMS. With that being said, I rather prefer to stick with the Netlify family

**Comment by duranmla** [comment]
With that being said, if there is no further opinions or challenge I will continue tomorrow with #1
