### ISSUE TITLE
Add Netlify logo to the footer

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#30]
**What:** Add Netlify logo to the footer

**Why:** Netlify added changed our billing plan to the Open Source one. In return, we have to add the logo somewhere in our website

**How:**

- Add Netlify logo to the footer. Logo can be found here https://www.netlify.com/press/#badges

**Comment by duranmla** [comment]
We will use what is already at academics https://academics.debtcollective.org/ use the same footer component
