### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#42]
**What:** Add Google Analytics

**Why:** To have data about our visitors

**How:**

We can either integrate this using the Google Analytics snippet or by integrating Google Tag Manager

**Comment by duranmla** [comment]
The commitment is to have insight about demographics (where geographically the users come from) and some traffics insight (the amount of visits) and knowing the amount of people joining into the campaign (this last one is being covered also by #19 )
