### ISSUE TITLE
Preview on CMS is missing

### ISSUE THREAD

**Issue by duranmla** [debtcollective/student-debt-campaign#47]
Add correct support of preview templates within the CMS.

**Current:**
![image](https://user-images.githubusercontent.com/1425162/68528820-ff340b80-02f7-11ea-8713-cf9642c88c8a.png)

**Expected:**
We should be able to render the page as it would be rendered with the content

**Comment by duranmla** [comment]
The current status of the related branch `cms-preview` shows the preview but we still need to understand why the live editing is not working.

![image](https://user-images.githubusercontent.com/1425162/70647582-8e12ab80-1c49-11ea-8cad-00f1d097f72f.png)

**Comment by duranmla** [comment]
The error I have 
![image](https://user-images.githubusercontent.com/1425162/70654169-1139fe80-1c56-11ea-8eaf-3836c5f46d2f.png)

**Comment by orlando** [comment]
Linking this comment https://github.com/gatsbyjs/gatsby/issues/19898

**Comment by duranmla** [comment]
I have added the solution that the thread above suggest but it doesn't fix the interactivity issue. I am looking at it now.
