### ISSUE TITLE
Connect Action title and Description to the CMS

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#72]
**What:** Connect Action title and Description to the CMS

**Why:** To be able to change copy from the CMS

**How:**

- Create a new collection in Netlify called **Actions**
- Actions have a unique slug and this is what we use to identify them, use this as the key for the data

**Comment by duranmla** [comment]
According to the PR seems like this is closed. If that's the thing, let's closed it.

**Comment by orlando** [comment]
@duranmla no is not, I just mentioned this issue there

**Comment by duranmla** [comment]
The implemented approach was to have all the titles and description within the same page. In the end, it wasn't clear enough so we have decided to use https://github.com/debtcollective/campaign-api/blob/master/seeds/002_actions.js and create a separate slug edition page within the actions collection.

**Comment by duranmla** [comment]
After the latest changes now the CMS looks like ![http://recordit.co/AtgcQ32OL6](http://recordit.co/AtgcQ32OL6.gif) now what we need is to update the client only pages of action to get the CMS content
