### ISSUE TITLE
Bump the campaign members numbers

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#86]
**What:** Bump the campaign members numbers

**Why:** We want to give the sense that there are more people in the campaign than the ones we have in the database. The idea is to bump the number by 50~
 
**How:**

- Bump the count in the database by 50~ for each section.

**Comment by duranmla** [comment]
Makes sense because we have a community that we yet don't know how to reflect within those numbers. And this are numbers that are stored within another database for this flow but still part of the same main goal.
