### ISSUE TITLE
Correct Data Dues action copy

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#87]
**What:** Correct Data Dues action copy

**Why:** To have the language aligned with what our users are expecting

**How:**

- Implement changes described in the attached PDF below

[Debt Data.pdf](https://github.com/debtcollective/student-debt-campaign/files/3947101/Debt.Data.pdf)

**Comment by duranmla** [comment]
I guess this should be within the _release 1.0.0_? if so let's add to it.
