### ISSUE TITLE
FlowType error within Join usage

### ISSUE THREAD

**Issue by duranmla** [debtcollective/student-debt-campaign#89]
Within `src/pages/app.js:29` the props are not matching with `src/components/Join/index.js:15` make sure to update to avoid flow type errors

![image](https://user-images.githubusercontent.com/1425162/70640547-636e2600-1c3c-11ea-8fb3-eb089b2832d6.png)

**Comment by orlando** [comment]
@duranmla oh I see what you mean now, this prop is passed by the Router, `:motive` gets populated with whatever the user puts in that URL. We have validations to allow only the ones we need.

I've should added a "ignore flow" comment instead

**Comment by duranmla** [comment]
As I mentioned in slack instead disable we want to check the type definition (like a type we can get from the router lib) or/and add the type definition within the Join section. In that sense, we have the flow benefits and not bypass it
